# Generated by Django 4.2.4 on 2023-08-19 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shoplist", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="bought",
            new_name="purchased",
        ),
    ]
