# Generated by Django 4.2.4 on 2023-08-23 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("shoplist", "0002_rename_bought_item_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="purchased_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
